In [1]:
# numpy 001
# axes => eixos

In [2]:
# import de bibliotecas
import numpy as np

In [3]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [4]:
# tipo de dados da array int64
a.dtype

dtype('int64')

In [6]:
b = np.array([5.2, 3.5, 6.0])
b

array([5.2, 3.5, 6. ])

In [8]:
# tipo de dados da array float64
b.dtype

dtype('float64')

In [9]:
# Criando uma matriz de duas linhas e três colunas
c = np.array([(1.5, 2, 6), (5, 6.3, 8)])
c

array([[1.5, 2. , 6. ],
       [5. , 6.3, 8. ]])

In [11]:
# Podemos criar uma matriz de valores complexos
d = np.array([[1, 2], [3, 4]], dtype = complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [14]:
# Matriz zerada 3 x 3
e = np.zeros((3, 3))
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# Matriz de 1
f = np.ones((2, 3, 3), dtype=np.int16)
f

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [19]:
# Função similar ao range de python para criar uma array com valores dentro de um range. (inicio, fim, step)
np.arange(12, 30, 5)

array([12, 17, 22, 27])

In [21]:
np.arange(0, 2, 0.15)

array([0.  , 0.15, 0.3 , 0.45, 0.6 , 0.75, 0.9 , 1.05, 1.2 , 1.35, 1.5 ,
       1.65, 1.8 , 1.95])

In [25]:
# Com valores decimais é mais recomendado utilizar linspace que determina o inicio, fim e quantos valores que no meio
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])