In [1]:
# C-means
# Atribui o cluster de forma percentual.

In [2]:
# Import das bibliotecas
import numpy as np
from sklearn import datasets
from sklearn.metrics import confusion_matrix
import skfuzzy

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [4]:
# Carregamento da base iris com datasets
iris = datasets.load_iris()

In [5]:
# Aplicação de algoritmo definindo 3 cluster(c = 3) e passando a matriz transposta(iris.data.T). Os outros parâmetros são obrigatórios
# e são os default indicados na documentação
r = skfuzzy.cmeans(data = iris.data.T, c = 3, m = 2, error = 0.005, maxiter = 1000, init = None)

In [6]:
# Obtendo as porcentagens de um registro pertencer a um cluster, que está na posição 1, da matriz retornada
previsoes_percentagem = r[1]
previsoes_percentagem

array([[9.96623645e-01, 9.75833981e-01, 9.79813825e-01, 9.67402858e-01,
        9.94469906e-01, 9.34534393e-01, 9.79479099e-01, 9.99546925e-01,
        9.30332960e-01, 9.82708955e-01, 9.68024983e-01, 9.92130215e-01,
        9.70619098e-01, 9.22927361e-01, 8.89713132e-01, 8.41280317e-01,
        9.46900741e-01, 9.96652167e-01, 9.04079552e-01, 9.79178800e-01,
        9.68579136e-01, 9.84824432e-01, 9.58641213e-01, 9.79405132e-01,
        9.66888392e-01, 9.73543557e-01, 9.94838664e-01, 9.93344620e-01,
        9.93673137e-01, 9.79498675e-01, 9.78708393e-01, 9.74345739e-01,
        9.38492686e-01, 9.04129103e-01, 9.85052144e-01, 9.84986271e-01,
        9.64166276e-01, 9.90888775e-01, 9.39646116e-01, 9.98287800e-01,
        9.94727335e-01, 8.50643101e-01, 9.52586909e-01, 9.79270093e-01,
        9.45230427e-01, 9.72124758e-01, 9.76780403e-01, 9.74203700e-01,
        9.77208592e-01, 9.97071057e-01, 4.45730872e-02, 2.92106430e-02,
        3.12500550e-02, 4.92049500e-02, 2.41562374e-02, 5.733562

In [7]:
# Visualização da probabilidade de um registro pertencer a cada um dos cluster(o somatório é 1.0, que indica 100%)
for x in range(150):
    print(previsoes_percentagem[0][x], previsoes_percentagem[1][x], previsoes_percentagem[2][x] )

0.9966236449673542 0.002304466308793688 0.0010718887238521482
0.9758339807897772 0.01666343043483287 0.007502588775389852
0.9798138245921675 0.01376859461292029 0.006417580794912281
0.9674028581907114 0.02248351781615367 0.01011362399313484
0.9944699056576493 0.0037622150137463675 0.001767879328604451
0.9345343926645708 0.04483531294842301 0.020630294387006205
0.9794790994475981 0.014013226540503555 0.006507674011898459
0.9995469249309806 0.0003117838751579398 0.00014129119386134583
0.930332959625675 0.04775310185586524 0.021913938518459953
0.9827089547172736 0.011945963465148531 0.005345081817577926
0.9680249831356836 0.02176956594852293 0.010205450915793425
0.9921302150081028 0.0054369282177969625 0.002432856774100051
0.9706190975599035 0.020198504671925136 0.009182397768171369
0.922927360676413 0.05182574052279491 0.025246898800792075
0.8897131324389254 0.07264142296630875 0.03764544459476591
0.8412803172676301 0.10439308294907305 0.05432659978329684
0.9469007411948792 0.03559687416

In [8]:
# argmax está pegando o maior valor e colocando como o indicador do cluster ao qual pertence o dado
previsoes = previsoes_percentagem.argmax(axis = 0)
previsoes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1])

In [9]:
# Matriz confusão
resultados = confusion_matrix(iris.target, previsoes)
resultados

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0, 13, 37]])